name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/trigger.yaml"
      - ".github/workflows/deploy-hub.yaml"
  schedule:
    - cron: '0 0,12 * * *'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch
      run: |
        sudo apt-get update -y
        sudo apt-get install python3 python3-pip -y
        pip install PyGithub --break-system-packages
        python3 ./fetch-build.py