name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/trigger.yaml"
      - ".github/workflows/deploy-hub.yaml"
  schedule:
    - cron: '0 0,12 * * *'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Fetch
      run: |
        sudo apt-get update
        sudo apt-get install python3 -y
        python3 ./cache.py

    - name: Upload
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: web
        FOLDER: cache
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}